version: '2'
services:
  vault-unseal:
    image: andrewsav/vault-unseal
    tty: true
    environment:
      #- VU_DEBUG=1
      - VU_VAULT_URL=https://vault.test.bat.nz
      - VU_TIME_INTERVAL_SECONDS=10
      - VU_UNSEAL_KEY_1=KK8LQnb1ABSaj+U/aFQSwuKEz2xGM6rfZXon6w154Vok
      - VU_UNSEAL_KEY_2=qTAcxyhQYsK71tSn9scamcdBAjXryGnXws1tKvFmQ+Nh
      - VU_UNSEAL_KEY_3=MBP7AtdrdRo66SaBTcWGtDbiGHMvCNbhbkjgWeto9ZyD
      - VU_UNSEAL_KEY_4=A0+rUNwX4Zl64wk/09k3gDSRo24RV/g4eWKBRFHmTFO3
      - VU_UNSEAL_KEY_5=46oyotNKx+DyK9wcZgur7OzLCTPjeNkREGHssh/xFEXM
      - VU_GOLDFISH_URL=https://goldfish.test.bat.nz
      - VU_GOLDFISH_ID=5b3d2fe0-2ef7-8335-13a5-3689bef2d1d3
      - VU_GOLDFISH_SECRET=02d1c547-805b-ba4e-baf3-9fa7663ca8bc
